"""Initial migration

Revision ID: 3e4caf632902
Revises: 
Create Date: 2024-10-15 14:13:34.250469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4caf632902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', name='levels'), nullable=False),
    sa.Column('question', sa.String(length=400), nullable=False),
    sa.Column('correct_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.Column('datetime_shown', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)

    op.create_table('options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'option_id')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index('ix_question_option', ['question_id', 'option_id'], unique=True)

    op.create_foreign_key(
    'fk_correct_option_id', 'questions', 'options',
    ['id', 'correct_id'], ['question_id', 'option_id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index('ix_question_option')

    op.drop_table('options')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_id'))

    op.drop_table('questions')
    # ### end Alembic commands ###
